name: Deploy Develop to QA Split

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - qa_split
  push:
    branches:
      - qa_split

jobs:
  deploy_qa_split:
    runs-on: windows-latest
    steps:
      - name: Checkout c贸digo fuente
        uses: actions/checkout@v4

      - name: Configurar entorno QA Split
        shell: pwsh
        run: |
          Write-Output "Configurando c贸digo para QA Split"

      - name: Configurnado entorno en QA Split
        shell: pwsh
        run: |
          Write-Output "Confirgurando c贸digo la versi贸n desde Develop en QA Split"
